### ISSUE TITLE
fml tiny dusts and their stupid nuggets smelting

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#231]
Submitter: `Vyraal1#0001`
Body: `OwO issue "fml tiny dusts and their stupid nuggets smelting"`
Attachments:

**Comment by Saereth** [comment]
?? which ones

**Comment by Saereth** [comment]
consolidating, osmium from this post, need to figure out all effected
https://github.com/Vyraal1/FTB-Interactions/issues/218

**Comment by whizzball1** [comment]
Tiny cobalt dust

**Comment by Saereth** [comment]
most of these are not an issue since you had to have ingots of it to begin with, will review this list tomorrow and see which ones are actually an issue, most likely just any that can be produced by an electrolyzation/centrifuging process thus bypassing blast furnacing, we should also check fluid extractor for any of these recipes as well
