### ISSUE TITLE
Leutenium(sp) cannot be acquired through fusing, nor ore

### ISSUE THREAD

**Issue by TeamDman** [Vyraal1/FTB-Interactions#607]
Submitter: `Interactions#0220`
Body: `**[IRSmoh_]** OwO issue "Leutenium(sp) cannot be acquired through fusing, nor ore"`
Attachments:

**Comment by Saereth** [comment]
What is this even needed for?

**Comment by Vyraal1** [comment]
Two things, Raw Carbon Fibers (instead of Palladium) 
![image](https://user-images.githubusercontent.com/26587049/54092480-f6eb9100-4362-11e9-88a4-e169c359ed9c.png)

and Americium from Fusion reactor when mixed with Chrome
![image](https://user-images.githubusercontent.com/26587049/54092485-04088000-4363-11e9-9af4-4961e790636a.png)

Gona add small dust % as a thermal centrifuge monazite byproduct

**Comment by Saereth** [comment]
recipe added
